Repository larq/zoo, pull requests merged in 2019-11, with the labels that each got.

#83 Run unit tests in parallel using `pytest-xdist`
  .github/workflows/unittest.yml
  CONTRIBUTING.md
  setup.py
Labels: internal-improvement

#84 Upgrade black
  .github/workflows/lint.yml
Labels: dependencies

#87 Bump larq@0.8.0
  .github/workflows/unittest.yml
  README.md
  setup.py
Labels: breaking-change

#88 Add names to all models
  larq_zoo/binarynet.py
  larq_zoo/birealnet.py
  larq_zoo/densenet.py
  larq_zoo/dorefanet.py
  larq_zoo/resnet_e.py
  larq_zoo/xnornet.py
Labels: feature

#90 Bump larq to 0.8.1
  setup.py
Labels: dependencies

#91 Bump version to 0.5
  setup.py
Labels: skip-changelog
