Repository larq/zoo, pull requests merged in 2020-12, with the labels that each got.

#265 Add BinaryAlexNet reference to docstring of exported function...
  larq_zoo/literature/binary_alex_net.py
Labels: documentation

#262 Add support for TensorFlow 2.4
  .github/workflows/unittest.yml
  larq_zoo/core/model_factory.py
  larq_zoo/core/utils.py
  larq_zoo/literature/binary_alex_net.py
  larq_zoo/literature/birealnet.py
  larq_zoo/literature/densenet.py
  larq_zoo/literature/dorefanet.py
  larq_zoo/literature/meliusnet.py
  larq_zoo/literature/real_to_bin_nets.py
  larq_zoo/literature/resnet_e.py
  larq_zoo/literature/xnornet.py
  larq_zoo/sota/quicknet.py
Labels: feature

#266 :arrow_up: 2.0.2
  setup.py
Labels: skip-changelog

#269 Loosen zookeeper requirements
  setup.py
Labels: internal-improvement

#270 :arrow_up: 2.0.3
  setup.py
Labels: skip-changelog
