Repository larq/zoo, pull requests merged in 2020-10, with the labels that each got.

#244 Fix CI by pinning TFDS for old TF versions.
  .github/workflows/unittest.yml
  tests/train_test.py
Labels: bug

#249 Run linting in Python 3.8
  .github/workflows/lint.yml
  setup.cfg
Labels: internal-improvement

#248 Add QuickNet v1 architecture
  larq_zoo/sota/__init__.py
  larq_zoo/sota/quicknet.py
  larq_zoo/training/learning_schedules.py
  larq_zoo/training/main.py
  larq_zoo/training/multi_stage_experiments.py
  larq_zoo/training/sota_experiments.py
  tests/models_test.py
  tests/train_test.py
Labels: breaking-change

#250 :arrow_up: 2.0.0
  setup.py
Labels: skip-changelog

#251 Remove patch number from model versions
  larq_zoo/sota/quicknet.py
Labels: internal-improvement

#254 Add __version__ property.
  larq_zoo/__init__.py
  setup.py
  tests/version_test.py
Labels: internal-improvement

#255 :arrow_up: 2.0.1
  setup.py
Labels: skip-changelog
