Repository larq/zoo, pull requests merged in 2020-04, with the labels that each got.

#147 Simplify testing and dummy data generation
  larq_zoo/training/data.py
  tests/dummy_datasets.py
  tests/fixtures/dummy_datasets/dummy_oxford_flowers102/2.0.0/dataset_info.json
  tests/fixtures/dummy_datasets/dummy_oxford_flowers102/2.0.0/dummy_oxford_flowers102-train.tfrecord-00000-of-00001
  tests/fixtures/dummy_datasets/dummy_oxford_flowers102/2.0.0/image.image.json
  tests/train_test.py
Labels: internal-improvement

#145 Add model metrics to docstrings
  larq_zoo/literature/binary_alex_net.py
  larq_zoo/literature/birealnet.py
  larq_zoo/literature/densenet.py
  larq_zoo/literature/dorefanet.py
  larq_zoo/literature/resnet_e.py
  larq_zoo/literature/xnornet.py
  larq_zoo/sota/quicknet.py
Labels: documentation

#146 Upload coverage report without token
  .github/workflows/unittest.yml
Labels: internal-improvement

#151 Render model summary in docs
  larq_zoo/literature/binary_alex_net.py
  larq_zoo/literature/birealnet.py
  larq_zoo/literature/densenet.py
  larq_zoo/literature/dorefanet.py
  larq_zoo/literature/resnet_e.py
  larq_zoo/literature/xnornet.py
  larq_zoo/sota/quicknet.py
Labels: documentation

#152 Only publish releases on pypi that start with v*
  .github/workflows/publish.yml
Labels: skip-changelog

#153 Fix workflow syntax
  .github/workflows/publish.yml
Labels: skip-changelog

#154 Simplify QuickNet weight-loading to be consistent with BDN.
  larq_zoo/sota/quicknet.py
Labels: internal-improvement

#156 Drop support for TF 1.14.
  .github/workflows/unittest.yml
  README.md
  setup.py
Labels: breaking-change

#150 Real to bin training
  larq_zoo/literature/real_to_bin_nets.py
  larq_zoo/training/knowledge_distillation/__init__.py
  larq_zoo/training/knowledge_distillation/knowledge_distillation.py
  larq_zoo/training/knowledge_distillation/multi_stage_training.py
  larq_zoo/training/learning_schedules.py
  larq_zoo/training/multi_stage_experiments.py
  larq_zoo/training/train.py
  tests/train_test.py
Labels: feature

#142 MeliusNet22 implementation
  larq_zoo/core/utils.py
  larq_zoo/literature/__init__.py
  larq_zoo/literature/meliusnet.py
  tests/models_test.py
Labels: feature

#158 Add test to ensure that notop-weight are correct
  larq_zoo/literature/binary_alex_net.py
  larq_zoo/literature/densenet.py
  larq_zoo/literature/dorefanet.py
  larq_zoo/literature/meliusnet.py
  larq_zoo/literature/xnornet.py
  larq_zoo/sota/quicknet.py
  tests/models_test.py
Labels: bug

#149 Don't set quantizers as fields
  larq_zoo/core/model_factory.py
  larq_zoo/literature/binary_alex_net.py
  larq_zoo/literature/birealnet.py
  larq_zoo/literature/densenet.py
  larq_zoo/literature/dorefanet.py
  larq_zoo/literature/meliusnet.py
  larq_zoo/literature/real_to_bin_nets.py
  larq_zoo/literature/resnet_e.py
  larq_zoo/literature/xnornet.py
  larq_zoo/sota/quicknet.py
  larq_zoo/training/knowledge_distillation/knowledge_distillation.py
Labels: bug

#161 :arrow_up: v1.0.0
  setup.py
Labels: skip-changelog

#163 fix netron link, add summary
  larq_zoo/literature/real_to_bin_nets.py
Labels: documentation

#164 Use more optimized pooling function for R2B
  larq_zoo/literature/real_to_bin_nets.py
Labels: internal-improvement

#165 :arrow_up: 1.0.1
  setup.py
Labels: skip-changelog

#166 Resolve pre-processing test failures.
  .github/workflows/unittest.yml
  larq_zoo/core/utils.py
  setup.py
  tests/utils_test.py
Labels: internal-improvement

#168 Fix dataset mocking for TensorFlow 3.1.0
  larq_zoo/training/data.py
  setup.py
  tests/train_test.py
Labels: internal-improvement
