Repository larq/zoo, pull requests merged in 2020-06, with the labels that each got.

#175 Type hints update
  larq_zoo/training/knowledge_distillation/multi_stage_training.py
Labels: bug

#177 Fix entry point
  larq_zoo/training/main.py
  setup.py
Labels: bug

#178 Update version number to 1.0.3
  setup.py
Labels: skip-changelog

#179 Cleanup tests
  setup.py
  tests/models_test.py
  tests/train_test.py
  tests/utils_test.py
Labels: internal-improvement
