Repository larq/zoo, pull requests merged in 2020-07, with the labels that each got.

#185 Simplify CI and run training test in parallel
  .github/workflows/lint.yml
  .github/workflows/unittest.yml
  larq_zoo/__init__.py
  larq_zoo/core/utils.py
  setup.cfg
  setup.py
Labels: internal-improvement

#189 Update version number 1.0.4
  setup.py
Labels: skip-changelog

#190 :arrow_up: v1.0.5
  setup.py
Labels: skip-changelog

#209 Add TensorFlow 2.3 to CI matrix
  .github/workflows/unittest.yml
Labels: dependencies
