Repository larq/zoo, pull requests merged in 2020-03, with the labels that each got.

#121 Remove deprecated layer metrics kwarg
  larq_zoo/literature/resnet_e.py
  larq_zoo/sota/quicknet.py
  larq_zoo/sota/quicknet_large.py
Labels: internal-improvement

#122 Add meta info about Larq Zoo to README
  README.md
Labels: documentation

#131 Sync CI workflows with larq
  .github/workflows/lint.yml
  .github/workflows/publish.yml
  .github/workflows/release-notes.yml
  .github/workflows/unittest.yml
  CONTRIBUTING.md
Labels: internal-improvement

#132 Update version number to 1.0.b3
  setup.py
Labels: skip-changelog

#134 Add support for TensorFlow 2.2
  .github/workflows/unittest.yml
  larq_zoo/core/utils.py
Labels: bug

#135 Explicitly compute softmax in float32
  larq_zoo/literature/binary_alex_net.py
  larq_zoo/literature/birealnet.py
  larq_zoo/literature/densenet.py
  larq_zoo/literature/dorefanet.py
  larq_zoo/literature/resnet_e.py
  larq_zoo/literature/xnornet.py
  larq_zoo/sota/quicknet.py
  larq_zoo/sota/quicknet_large.py
Labels: internal-improvement

#136 Implement one-padding and reduce number of SE blocks for QuickNet
  larq_zoo/sota/quicknet.py
  larq_zoo/sota/quicknet_large.py
  setup.py
Labels: feature

#138 Refactor quicknets and remove duplication
  larq_zoo/sota/__init__.py
  larq_zoo/sota/quicknet.py
  larq_zoo/sota/quicknet_large.py
Labels: internal-improvement

#139 Update version number 1.0.b4
  setup.py
Labels: skip-changelog

#140 Add names to quicknet models
  larq_zoo/sota/quicknet.py
Labels: bug
