Repository larq/zoo, pull requests merged in 2020-02, with the labels that each got.

#104 Fix GitHub Actions workflows
  .github/workflows/lint.yml
  .github/workflows/unittest.yml
Labels: internal-improvement

#92 Zookeeper v1.0
  larq_zoo/__init__.py
  larq_zoo/binary_alex_net.py
  larq_zoo/binarynet.py
  larq_zoo/birealnet.py
  larq_zoo/data.py
  larq_zoo/datasets.py
  larq_zoo/densenet.py
  larq_zoo/dorefanet.py
  larq_zoo/model_factory.py
  larq_zoo/resnet_e.py
  larq_zoo/train.py
  larq_zoo/utils.py
  larq_zoo/xnornet.py
  setup.py
  tests/data_test.py
  tests/models_test.py
  tests/train_test.py
Labels: dependencies, internal-improvement

#105 :arrow_up: v1.0.b1
  setup.py
Labels: skip-changelog

#109 Move Tasks to larq_zoo.experiments
  larq_zoo/binary_alex_net.py
  larq_zoo/birealnet.py
  larq_zoo/densenet.py
  larq_zoo/dorefanet.py
  larq_zoo/experiments.py
  larq_zoo/resnet_e.py
  larq_zoo/train.py
  larq_zoo/xnornet.py
  setup.py
  tests/train_test.py
Labels: internal-improvement

#107 QuickNet
  larq_zoo/__init__.py
  larq_zoo/quicknet.py
  tests/models_test.py
Labels: feature, models

#108 Split zoo into `literature` and `sota` submodule
  README.md
  larq_zoo/__init__.py
  larq_zoo/experiments.py
  larq_zoo/literature/__init__.py
  larq_zoo/literature/binary_alex_net.py
  larq_zoo/literature/birealnet.py
  larq_zoo/literature/densenet.py
  larq_zoo/literature/dorefanet.py
  larq_zoo/literature/quicknet.py
  larq_zoo/literature/resnet_e.py
  larq_zoo/literature/xnornet.py
  larq_zoo/sota/__init__.py
  tests/models_test.py
Labels: breaking-change

#111 Move QuickNet into sota module
  larq_zoo/literature/__init__.py
  larq_zoo/sota/__init__.py
  larq_zoo/sota/quicknet.py
  tests/models_test.py
Labels: internal-improvement

#110 Improved Linting
  .github/workflows/lint.yml
  .gitignore
  larq_zoo/__init__.py
  larq_zoo/literature/densenet.py
  larq_zoo/utils.py
  setup.cfg
  setup.py
Labels: internal-improvement

#114 Fix docstring rendering on the website
  larq_zoo/literature/binary_alex_net.py
  larq_zoo/literature/birealnet.py
  larq_zoo/literature/densenet.py
  larq_zoo/literature/dorefanet.py
  larq_zoo/literature/resnet_e.py
  larq_zoo/literature/xnornet.py
  larq_zoo/sota/quicknet.py
  larq_zoo/sota/quicknet_large.py
Labels: documentation

#113 Point to `larq/docs`
  README.md
Labels: documentation

#116 fix argument ordering
  larq_zoo/literature/resnet_e.py
  larq_zoo/literature/xnornet.py
  larq_zoo/sota/quicknet.py
  larq_zoo/sota/quicknet_large.py
Labels: documentation

#117 Input shape docstring
  larq_zoo/literature/binary_alex_net.py
  larq_zoo/literature/birealnet.py
  larq_zoo/literature/densenet.py
  larq_zoo/literature/dorefanet.py
  larq_zoo/literature/resnet_e.py
  larq_zoo/literature/xnornet.py
  larq_zoo/sota/quicknet.py
  larq_zoo/sota/quicknet_large.py
Labels: documentation

#118 Bump version to 1.0.b2
  setup.py
Labels: skip-changelog

#119 Test model training on a dummy dataset of four images
  larq_zoo/train.py
  tests/__init__.py
  tests/dummy_datasets.py
  tests/fixtures/dummy_datasets/dummy_oxford_flowers102/2.0.0/dataset_info.json
  tests/fixtures/dummy_datasets/dummy_oxford_flowers102/2.0.0/dummy_oxford_flowers102-train.tfrecord-00000-of-00001
  tests/fixtures/dummy_datasets/dummy_oxford_flowers102/2.0.0/image.image.json
  tests/train_test.py
Labels: internal-improvement
