Repository larq/zoo, pull requests merged in 2021-05, with the labels that each got.

#308 :arrow_up: 2.0.7
  setup.py
Labels: skip-changelog

#309 Document TF 2.5 and Python 3.9 compatibility
  .github/workflows/unittest.yml
  README.md
  setup.py
Labels: documentation

#316 Rename `master` -> `main`.
  .github/workflows/lint.yml
  .github/workflows/release-notes.yml
  .github/workflows/unittest.yml
  README.md
  setup.py
Labels: skip-changelog

#317 Pin test dependencies.
  setup.py
Labels: internal-improvement

#320 Use 1x1 convolutions to improve BinaryAlexNet latency on Compute Engine
  larq_zoo/literature/binary_alex_net.py
Labels: feature

#321 Update to TF 2.5 stable on CI
  .github/workflows/lint.yml
  .github/workflows/unittest.yml
Labels: internal-improvement

#322 :arrow_up: 2.1.0
  setup.py
Labels: skip-changelog
