Repository larq/zoo, pull requests merged in 2021-01, with the labels that each got.

#274 Loosen zookeeper requirements
  setup.py
Labels: dependencies

#275 :arrow_up: 2.0.4
  setup.py
Labels: internal-improvement

#276 Fix bug when cloning QuickNet.
  larq_zoo/sota/quicknet.py
Labels: bug

#277 :arrow_up: v2.0.5
  setup.py
Labels: skip-changelog

#278 Update TF package versions on CI and in README.
  .github/workflows/lint.yml
  .github/workflows/unittest.yml
  README.md
Labels: internal-improvement
